import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Plus, RefreshCw, Sheet, Trash2, WalletCards } from "lucide-react";
import { AdminTabs } from "@/components/AdminTabs";
import { checkAdminUnlocked, supabase } from "@/lib/fares.functions";

export const Route = createFileRoute("/admin/airline-balance")({
  ssr: false,
  head: () => ({ meta: [
    { title: "Airline Balance Dashboard · Rohi Admin" },
    { name: "description", content: "Track airline accounts, ticket sales, credits, debits and profit across monthly and yearly periods." },
    { property: "og:title", content: "Airline Balance Dashboard · Rohi Admin" },
    { property: "og:description", content: "A focused airline balance and profit dashboard for Rohi International Travels." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ]}),
  component: AirlineBalancePage,
});

type Airline = { id: string; name: string; iata_code: string };
type Entry = { id: string; airline_id: string; entry_date: string; agent_name: string; pax_name: string; sector: string; pnr: string; ticket_sales: number; debit_in_id: number; credit_from_id: number; pax_contact: string; void_charges: number; ledger_entry: string };
type Account = { id: string; airline_id: string; account_label: string; opening_balance: number; sheet_url: string | null };
const money = (n: number) => Number(n || 0).toLocaleString("en-PK");
const empty = { airline_id: "", entry_date: new Date().toISOString().slice(0, 10), agent_name: "", pax_name: "", sector: "", pnr: "", ticket_sales: 0, debit_in_id: 0, credit_from_id: 0, pax_contact: "", void_charges: 0, ledger_entry: "" };

function AirlineBalancePage() {
  const qc = useQueryClient();
  const [showEntry, setShowEntry] = useState(false);
  const [showAccount, setShowAccount] = useState(false);
  const [airlineId, setAirlineId] = useState("all");
  const [period, setPeriod] = useState<"month" | "year">("month");
  const [form, setForm] = useState<any>(empty);
  const [account, setAccount] = useState({ airline_id: "", account_label: "Primary Account", opening_balance: 0, sheet_url: "" });
  const { data: status } = useQuery({ queryKey: ["admin", "status"], queryFn: () => checkAdminUnlocked() });
  const { data: airlines = [] } = useQuery({ queryKey: ["airlines"], queryFn: async () => (await supabase.from("airlines").select("id,name,iata_code").order("name")).data as Airline[] });
  const { data: entries = [], refetch } = useQuery({ queryKey: ["airline-balance-entries"], queryFn: async () => (await supabase.from("airline_balance_entries").select("*").order("entry_date", { ascending: false })).data as Entry[] });
  const { data: accounts = [] } = useQuery({ queryKey: ["airline-balance-accounts"], queryFn: async () => (await supabase.from("airline_balance_accounts").select("*")).data as Account[] });
  useEffect(() => { const c = supabase.channel("airline-balance-live").on("postgres_changes", { event: "*", schema: "public", table: "airline_balance_entries" }, () => qc.invalidateQueries({ queryKey: ["airline-balance-entries"] })).subscribe(); return () => { supabase.removeChannel(c); }; }, [qc]);
  const visible = useMemo(() => entries.filter(e => airlineId === "all" || e.airline_id === airlineId).filter(e => { const d = new Date(e.entry_date); const now = new Date(); return period === "year" ? d.getFullYear() === now.getFullYear() : d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth(); }), [entries, airlineId, period]);
  const totals = useMemo(() => visible.reduce((a, e) => ({ sales: a.sales + +e.ticket_sales, debit: a.debit + +e.debit_in_id, credit: a.credit + +e.credit_from_id, voids: a.voids + +e.void_charges }), { sales: 0, debit: 0, credit: 0, voids: 0 }), [visible]);
  const balance = totals.credit - totals.debit;
  async function addEntry(e: React.FormEvent) { e.preventDefault(); const { error } = await supabase.from("airline_balance_entries").insert(form); if (error) return alert(error.message); setShowEntry(false); setForm({ ...empty, airline_id: form.airline_id }); await refetch(); }
  async function addAccount(e: React.FormEvent) { e.preventDefault(); const { error } = await supabase.from("airline_balance_accounts").insert(account); if (error) return alert(error.message); setShowAccount(false); qc.invalidateQueries({ queryKey: ["airline-balance-accounts"] }); }
  async function removeEntry(id: string) { if (!confirm("Remove this ledger entry?")) return; await supabase.from("airline_balance_entries").delete().eq("id", id); refetch(); }
  if (!status?.unlocked) return <div className="p-10 text-center">Admin session required.</div>;
  return <div className="min-h-screen bg-background"><header className="border-b border-border bg-navy text-navy-foreground"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-4 py-4"><div className="flex items-center gap-3"><WalletCards className="h-5 w-5 text-gold" /><div><p className="font-serif text-lg font-black">Admin Panel</p><p className="text-[10px] tracking-widest text-white/60">Airline balance control centre</p></div><button onClick={() => refetch()} title="Refresh" className="ml-3 rounded p-2 hover:bg-white/10"><RefreshCw className="h-4 w-4" /></button></div><div className="flex gap-2"><button onClick={() => setShowAccount(true)} className="inline-flex items-center gap-2 rounded-md border border-gold/50 px-3 py-2 text-xs font-bold text-gold"><Plus className="h-3.5 w-3.5" /> Airline Account</button><button onClick={() => setShowEntry(true)} className="inline-flex items-center gap-2 rounded-md bg-gold px-3 py-2 text-xs font-bold text-gold-foreground"><Plus className="h-3.5 w-3.5" /> Add Entry</button></div></div><AdminTabs /></header>
  <main className="mx-auto max-w-[1600px] space-y-5 px-4 py-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-serif text-2xl font-black text-foreground">Airline Balance Dashboard</h1><p className="text-xs text-muted-foreground">One view for airline accounts, ticket movement and profitability.</p></div><div className="flex gap-2"><select value={airlineId} onChange={e => setAirlineId(e.target.value)} className="rounded-md border border-border bg-card px-3 py-2 text-xs"><option value="all">All airlines</option>{airlines.map(a => <option key={a.id} value={a.id}>{a.name} ({a.iata_code})</option>)}</select><div className="flex rounded-md border border-border bg-card p-1"><button onClick={() => setPeriod("month")} className={`px-3 py-1 text-xs font-bold ${period === "month" ? "bg-navy text-white" : ""}`}>This month</button><button onClick={() => setPeriod("year")} className={`px-3 py-1 text-xs font-bold ${period === "year" ? "bg-navy text-white" : ""}`}>This year</button></div></div></div>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Ticket Sales", totals.sales, "text-navy"],["Debit In ID", totals.debit, "text-red-600"],["Credit From ID", totals.credit, "text-emerald-700"],["Balance", balance, balance >= 0 ? "text-emerald-700" : "text-red-600"],["Profit / Loss", totals.sales - totals.debit - totals.voids, "text-gold"]].map(([label, value, color]) => <div key={String(label)} className="rounded-lg border border-border bg-card p-4"><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-black ${color}`}>{money(Number(value))} <span className="text-[10px]">PKR</span></p></div>)}</section>
  <section className="grid gap-4 lg:grid-cols-3">{airlines.map(a => { const rows = entries.filter(e => e.airline_id === a.id); const acc = accounts.filter(x => x.airline_id === a.id); const bal = rows.reduce((s, e) => s + +e.credit_from_id - +e.debit_in_id, 0) + (acc[0]?.opening_balance || 0); return <div key={a.id} className="rounded-lg border border-border bg-card p-4"><div className="flex items-center justify-between"><div><p className="font-black text-foreground">{a.name}</p><p className="text-[10px] font-bold tracking-widest text-muted-foreground">{a.iata_code} · {acc.length || 0} account{acc.length === 1 ? "" : "s"}</p></div><BarChart3 className="h-5 w-5 text-gold" /></div><p className={`mt-4 text-2xl font-black ${bal >= 0 ? "text-emerald-700" : "text-red-600"}`}>{money(bal)} <span className="text-xs">PKR</span></p><p className="mt-1 text-[11px] text-muted-foreground">Current balance · {rows.length} ledger entries</p></div>})}</section>
  <div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[1200px] text-xs"><thead className="bg-navy text-[10px] uppercase tracking-wider text-gold"><tr>{["Sr #","Date","Agent Name","Pax Name","Sector","PNR","Ticket Sales","Debit In ID","Credit From ID","Balance","Pax Contact #","Void Charges","Profit","Ledger Entry",""].map(x => <th key={x} className="px-3 py-3 text-left">{x}</th>)}</tr></thead><tbody>{visible.map((e, i) => { const rowBal = +e.credit_from_id - +e.debit_in_id; const profit = +e.ticket_sales - +e.debit_in_id - +e.void_charges; return <tr key={e.id} className="border-b border-border hover:bg-muted/40"><td className="px-3 py-3">{i + 1}</td><td className="px-3 py-3 whitespace-nowrap">{e.entry_date}</td><td className="px-3 py-3">{e.agent_name}</td><td className="px-3 py-3 font-semibold">{e.pax_name}</td><td className="px-3 py-3">{e.sector}</td><td className="px-3 py-3 font-mono">{e.pnr}</td><td className="px-3 py-3 font-bold">{money(e.ticket_sales)}</td><td className="px-3 py-3 text-red-600">{money(e.debit_in_id)}</td><td className="px-3 py-3 text-emerald-700">{money(e.credit_from_id)}</td><td className={`px-3 py-3 font-black ${rowBal >= 0 ? "text-emerald-700" : "text-red-600"}`}>{money(rowBal)}</td><td className="px-3 py-3">{e.pax_contact}</td><td className="px-3 py-3">{money(e.void_charges)}</td><td className="px-3 py-3 font-black text-gold">{money(profit)}</td><td className="px-3 py-3">{e.ledger_entry || "—"}</td><td className="px-3 py-3"><button onClick={() => removeEntry(e.id)} title="Remove" className="text-destructive"><Trash2 className="h-4 w-4" /></button></td></tr>})}</tbody></table>{visible.length === 0 && <p className="p-10 text-center text-sm text-muted-foreground">No entries for this period.</p>}</div>
  <p className="flex items-center gap-2 text-xs text-muted-foreground"><Sheet className="h-4 w-4 text-emerald-700" /> Google Sheets destination can be stored per airline account for future ledger synchronization. Existing backup remains separate.</p></main>
  {showEntry && <Modal title="Add airline ledger entry" onClose={() => setShowEntry(false)}><form onSubmit={addEntry} className="grid gap-3 sm:grid-cols-2">{[["airline_id","Airline","select"],["entry_date","Date","date"],["agent_name","Agent Name"],["pax_name","Pax Name"],["sector","Sector"],["pnr","PNR"],["ticket_sales","Ticket Sales","number"],["debit_in_id","Debit In ID","number"],["credit_from_id","Credit From ID","number"],["pax_contact","Pax Contact #"],["void_charges","Void Charges","number"],["ledger_entry","Ledger Entry"]].map(([key,label,type]) => <label key={key} className="text-xs font-bold">{label}<>{type === "select" ? <select required value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded border border-border bg-background p-2"><option value="">Choose airline</option>{airlines.map(a => <option key={a.id} value={a.id}>{a.name} ({a.iata_code})</option>)}</select> : <input required={key === "airline_id"} type={type || "text"} value={form[key]} onChange={e => setForm({...form,[key]: type === "number" ? Number(e.target.value) : e.target.value})} className="mt-1 w-full rounded border border-border bg-background p-2" />}</></label>)}<button className="sm:col-span-2 rounded bg-navy p-2 text-xs font-bold text-white">Save ledger entry</button></form></Modal>}
  {showAccount && <Modal title="Add airline account" onClose={() => setShowAccount(false)}><form onSubmit={addAccount} className="grid gap-3"><label className="text-xs font-bold">Airline<select required value={account.airline_id} onChange={e => setAccount({...account,airline_id:e.target.value})} className="mt-1 w-full rounded border border-border bg-background p-2"><option value="">Choose airline</option>{airlines.map(a => <option key={a.id} value={a.id}>{a.name} ({a.iata_code})</option>)}</select></label><label className="text-xs font-bold">Account label<input value={account.account_label} onChange={e => setAccount({...account,account_label:e.target.value})} className="mt-1 w-full rounded border border-border bg-background p-2" /></label><label className="text-xs font-bold">Opening balance<input type="number" value={account.opening_balance} onChange={e => setAccount({...account,opening_balance:Number(e.target.value)})} className="mt-1 w-full rounded border border-border bg-background p-2" /></label><label className="text-xs font-bold">Google Sheet URL (optional)<input type="url" value={account.sheet_url} onChange={e => setAccount({...account,sheet_url:e.target.value})} placeholder="https://docs.google.com/spreadsheets/..." className="mt-1 w-full rounded border border-border bg-background p-2" /></label><button className="rounded bg-navy p-2 text-xs font-bold text-white">Save airline account</button></form></Modal>}</div>
}
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg bg-card p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="font-serif text-lg font-black">{title}</h2><button onClick={onClose} className="text-muted-foreground">×</button></div>{children}</div></div> }
