import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useMemo, useState } from "react";
import { Download, FileText, Plus, Save, Trash2, Wallet } from "lucide-react";
import { toast } from "sonner";
import { AdminTabs } from "@/components/AdminTabs";
import {
  createAccountsBookAccount,
  createAccountsBookLinkedEntry,
  createAccountsBookTransaction,
  createAccountsBookTransfer,
  createAccountsBookService,
  deleteAccountsBookService,
  deleteAccountsBookLinkedEntry,
  deleteAccountsBookAccount,
  deleteAccountsBookTransaction,
  listAccountsBook,
  updateAccountsBookOpening,
  updateAccountsBookTransaction,
  updateAccountsBookService,
} from "@/lib/accounts-book.functions";

export const Route = createFileRoute("/admin/accounts")({
  head: () => ({ meta: [{ title: "Rohi Accounts Desk — Rohi Admin" }] }),
  component: AccountsBookPage,
});

type Account = { id: string; name: string; kind: "cash" | "bank" | "wallet"; opening_balance: number; opening_balance_date?: string };
type Transaction = { id: string; account_id: string; entry_date: string; entry_type: string; category: string; party: string | null; description: string; amount: number; direct_cost: number; direction: "in" | "out"; source_type?: string | null; source_id?: string | null };
type Service = { id: string; name: string };
type Tab = "overview" | "cashbook" | "sales" | "expenses" | "accounts" | "reports" | "settings";

const salesCategories = ["Counter Sales", "Saudia Visa Process", "KV Visit Visa", "Group Tickets", "Umrah", "Insurance", "Protect", "Appointments", "Refunds"];
const expenseCategories = ["Personal Expense", "Office Expense"];
const vendorNames = ["General Vendor", "Airline Supplier", "Visa Supplier", "Office Supplier"];
const airlineNames = ["Fly Jinnah", "Flyadeal", "Flynas", "SalamAir", "Air Arabia", "PIA", "Airblue"];

const money = (value: number) => `${Math.round(Number(value) || 0).toLocaleString("en-PK")} PKR`;
const dateText = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`));
const emptyEntry = () => ({ entry_date: new Date().toISOString().slice(0, 10), entry_type: "sale", category: "Ticketing", party: "", description: "", amount: "", direct_cost: "0", account_id: "", direction: "in" as "in" | "out" });

function balance(account: Account, transactions: Transaction[]) {
  return Number(account.opening_balance || 0) + transactions.filter((row) => row.account_id === account.id).reduce((total, row) => total + (row.direction === "in" ? Number(row.amount) : -Number(row.amount)), 0);
}

function csvCell(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }
function downloadCsv(accounts: Account[], transactions: Transaction[]) {
  const accountName = new Map(accounts.map((account) => [account.id, account.name]));
  const rows = [["Date", "Type", "Category", "Party", "Description", "Account", "Amount", "Direction", "Direct Cost"], ...transactions.map((row) => [row.entry_date, row.entry_type, row.category, row.party ?? "", row.description, accountName.get(row.account_id) ?? "", row.amount, row.direction, row.direct_cost])];
  const blob = new Blob(["\ufeff" + rows.map((row) => row.map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `rohi-accounts-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url);
}

function printAccounts(accounts: Account[], transactions: Transaction[]) {
  const accountName = new Map(accounts.map((account) => [account.id, account.name]));
  const rows = transactions.map((row) => `<tr><td>${dateText(row.entry_date)}</td><td>${row.entry_type}</td><td>${row.description}</td><td>${accountName.get(row.account_id) ?? ""}</td><td>${money(row.amount)}</td></tr>`).join("");
  const popup = window.open("", "_blank");
  if (!popup) { toast.error("Allow pop-ups to print the accounts report"); return; }
  popup.document.write(`<html><head><title>Rohi Accounts Desk</title><style>body{font:12px Arial;color:#14202b;padding:30px}h1{margin:0 0 4px}p{color:#667;margin:0 0 20px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #ddd}th{font-size:10px;text-transform:uppercase;color:#667}</style></head><body><h1>ROHI INTERNATIONAL TRAVELS</h1><p>Accounts Desk / generated ${dateText(new Date().toISOString().slice(0, 10))}</p><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Account</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table></body></html>`); popup.document.close(); popup.focus(); setTimeout(() => popup.print(), 250);
}

function AccountsBookPage() {
  const queryClient = useQueryClient();
  const load = useServerFn(listAccountsBook);
  const createAccount = useServerFn(createAccountsBookAccount);
  const updateOpening = useServerFn(updateAccountsBookOpening);
  const createTransaction = useServerFn(createAccountsBookTransaction);
  const createLinkedEntry = useServerFn(createAccountsBookLinkedEntry);
  const createTransfer = useServerFn(createAccountsBookTransfer);
  const deleteLinkedEntry = useServerFn(deleteAccountsBookLinkedEntry);
  const deleteTransaction = useServerFn(deleteAccountsBookTransaction);
  const updateTransaction = useServerFn(updateAccountsBookTransaction);
  const deleteAccount = useServerFn(deleteAccountsBookAccount);
  const createService = useServerFn(createAccountsBookService);
  const updateService = useServerFn(updateAccountsBookService);
  const deleteService = useServerFn(deleteAccountsBookService);
  const { data, isLoading, error } = useQuery({ queryKey: ["accounts-book"], queryFn: () => load(), refetchInterval: 30000 });
  const [tab, setTab] = useState<Tab>("overview");
  const [showEntry, setShowEntry] = useState(false);
  const [showTransactionMenu, setShowTransactionMenu] = useState(false);
  const [showAccount, setShowAccount] = useState(false);
  const [workflow, setWorkflow] = useState<"sale" | "expense" | "transfer" | null>(null);
  const [selectedAccountId, setSelectedAccountId] = useState<string | null>(null);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [entry, setEntry] = useState(emptyEntry);
  const [editingTransaction, setEditingTransaction] = useState<string | null>(null);
  const [newAccount, setNewAccount] = useState({ name: "", kind: "bank" as Account["kind"], opening_balance: "0", opening_balance_date: new Date().toISOString().slice(0, 10) });
  const [newService, setNewService] = useState("");
  const accounts = (data?.accounts ?? []) as Account[];
  const transactions = (data?.transactions ?? []) as Transaction[];
  const services = (data?.services ?? []) as Service[];
  const filteredTransactions = transactions.filter((row) => (!fromDate || row.entry_date >= fromDate) && (!toDate || row.entry_date <= toDate));
  const cash = accounts.find((account) => account.kind === "cash");
  const selectedAccount = accounts.find((account) => account.id === selectedAccountId) ?? accounts.find((account) => account.kind !== "cash");
  const selectedAccountRows = selectedAccount ? filteredTransactions.filter((row) => row.account_id === selectedAccount.id).sort((a, b) => a.entry_date.localeCompare(b.entry_date)) : [];
  const totals = useMemo(() => filteredTransactions.reduce((out, row) => { if (row.entry_type === "sale") { out.sales += Number(row.amount); out.cost += Number(row.direct_cost); } if (row.entry_type === "expense") out.expenses += Number(row.amount); return out; }, { sales: 0, cost: 0, expenses: 0 }), [filteredTransactions]);

  const refresh = () => queryClient.invalidateQueries({ queryKey: ["accounts-book"] });
  const openingMutation = useMutation({ mutationFn: (payload: any) => updateOpening({ data: payload }), onSuccess: () => { refresh(); toast.success("Opening balance saved"); }, onError: (e) => toast.error(e.message) });
  const accountMutation = useMutation({ mutationFn: (payload: any) => createAccount({ data: payload }), onSuccess: () => { setShowAccount(false); refresh(); toast.success("Account added"); }, onError: (e) => toast.error(e.message) });
  const entryMutation = useMutation({ mutationFn: (payload: any) => createTransaction({ data: payload }), onSuccess: () => { setEntry(emptyEntry()); setShowEntry(false); refresh(); toast.success("Transaction saved"); }, onError: (e) => toast.error(e.message) });
  const editMutation = useMutation({ mutationFn: (payload: any) => updateTransaction({ data: payload }), onSuccess: () => { setEditingTransaction(null); setEntry(emptyEntry()); setShowEntry(false); refresh(); toast.success("Ledger entry updated"); }, onError: (e) => toast.error(e.message) });
  const linkedMutation = useMutation({ mutationFn: (payload: any) => createLinkedEntry({ data: payload }), onSuccess: () => { setWorkflow(null); refresh(); toast.success("Entry saved and linked to the ledger"); }, onError: (e) => toast.error(e.message) });
  const transferMutation = useMutation({ mutationFn: (payload: any) => createTransfer({ data: payload }), onSuccess: () => { setWorkflow(null); refresh(); toast.success("Transfer posted to both ledgers"); }, onError: (e) => toast.error(e.message) });
  const linkedDeleteMutation = useMutation({ mutationFn: (payload: any) => deleteLinkedEntry({ data: payload }), onSuccess: () => { refresh(); toast.success("Linked entry deleted"); }, onError: (e) => toast.error(e.message) });
  const deleteMutation = useMutation({ mutationFn: (id: string) => deleteTransaction({ data: id }), onSuccess: () => { refresh(); toast.success("Transaction deleted"); }, onError: (e) => toast.error(e.message) });
  const accountDeleteMutation = useMutation({ mutationFn: (id: string) => deleteAccount({ data: id }), onSuccess: () => { refresh(); toast.success("Account removed"); }, onError: (e) => toast.error(e.message) });
  const serviceCreateMutation = useMutation({ mutationFn: (payload: any) => createService({ data: payload }), onSuccess: () => { setNewService(""); refresh(); toast.success("Service added"); }, onError: (e) => toast.error(e.message) });
  const serviceUpdateMutation = useMutation({ mutationFn: (payload: any) => updateService({ data: payload }), onSuccess: () => { refresh(); toast.success("Service updated"); }, onError: (e) => toast.error(e.message) });
  const serviceDeleteMutation = useMutation({ mutationFn: (id: string) => deleteService({ data: id }), onSuccess: () => { refresh(); toast.success("Service removed"); }, onError: (e) => toast.error(e.message) });

  if (isLoading) return <div className="p-10 text-center">Loading Rohi Accounts Desk…</div>;
  if (error) return <div className="p-10 text-center text-destructive">{error.message}</div>;

  function submitEntry(event: React.FormEvent) { event.preventDefault(); const amount = Number(entry.amount); if (!entry.entry_date || !entry.account_id || !entry.category || !entry.description || amount <= 0 || Number(entry.direct_cost) < 0) { toast.error("Complete the date, account, category, description, and a valid amount"); return; } const payload = { ...entry, amount, direct_cost: Number(entry.direct_cost) || 0, party: entry.party || undefined }; if (editingTransaction) editMutation.mutate({ ...payload, id: editingTransaction }); else entryMutation.mutate(payload); }
  function setEntryType(type: string) { setEntry((current) => ({ ...current, entry_type: type, direction: type === "expense" ? "out" : "in" })); }

  const recent = [...filteredTransactions].sort((a, b) => b.entry_date.localeCompare(a.entry_date)).slice(0, 8);
  const cashRows = filteredTransactions.filter((row) => row.account_id === cash?.id).sort((a, b) => a.entry_date.localeCompare(b.entry_date));
  let cashRunning = Number(cash?.opening_balance || 0);
  function editEntry(row: Transaction) { setEditingTransaction(row.id); setEntry({ entry_date: row.entry_date, entry_type: row.entry_type, category: row.category, party: row.party ?? "", description: row.description, amount: String(row.amount), direct_cost: String(row.direct_cost), account_id: row.account_id, direction: row.direction }); setShowEntry(true); }

  return <div className="min-h-screen bg-background animate-premium-fade">
    <header className="border-b border-gold/20 bg-navy text-white"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-4 py-4"><div className="flex items-center gap-3"><Wallet className="h-5 w-5 text-gold" /><p className="font-serif text-lg font-black text-gold">ROHI Accounts Desk</p></div><div className="flex gap-2"><button onClick={() => downloadCsv(accounts, filteredTransactions)} className="rounded border border-white/20 px-3 py-2 text-xs font-bold"><Download className="mr-1 inline h-3 w-3" /> Excel / Sheets CSV</button><button onClick={() => printAccounts(accounts, filteredTransactions)} className="rounded border border-white/20 px-3 py-2 text-xs font-bold"><FileText className="mr-1 inline h-3 w-3" /> PDF / Print</button><button onClick={() => setShowTransactionMenu(true)} className="rounded bg-gold px-3 py-2 text-xs font-bold text-navy"><Plus className="mr-1 inline h-3 w-3" /> Add Transaction</button></div></div><AdminTabs /></header>
    <main className="mx-auto max-w-[1600px] space-y-5 p-6">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-gold">Live Supabase ledger</p><h1 className="font-serif text-3xl font-black text-navy">Accounts overview</h1><p className="text-sm text-muted-foreground">Cash, banks, sales, expenses, transfers and reports in one admin module.</p></div></div>
      <div className="flex flex-wrap gap-2">{(["overview", "cashbook", "sales", "expenses", "accounts", "reports", "settings"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded px-3 py-2 text-xs font-bold uppercase tracking-widest ${tab === item ? "bg-navy text-white" : "border border-navy/15 bg-white text-navy"}`}>{item === "cashbook" ? "Cash Book" : item === "accounts" ? "Banks & Wallet" : item}</button>)}</div>
      <div className="flex flex-wrap items-end gap-3 rounded-xl border border-navy/10 bg-white p-4 shadow-sm"><label className="text-xs font-bold text-navy">From date<input className="ml-2 rounded border px-2 py-1 font-normal" type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label className="text-xs font-bold text-navy">To date<input className="ml-2 rounded border px-2 py-1 font-normal" type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><button type="button" onClick={() => { setFromDate(""); setToDate(""); }} className="rounded border border-navy/15 px-3 py-2 text-xs font-bold text-navy">Clear dates</button><span className="text-xs text-muted-foreground">Showing {filteredTransactions.length} of {transactions.length} entries</span></div>
      {tab === "overview" && <><div className="grid gap-4 md:grid-cols-4">{[["Cash in hand", balance(cash ?? { id: "", name: "Cash", kind: "cash", opening_balance: 0 }, transactions)], ["Banks & wallets", accounts.filter((a) => a.kind !== "cash").reduce((sum, a) => sum + balance(a, transactions), 0)], ["Total sales", totals.sales], ["Net profit", totals.sales - totals.cost - totals.expenses]].map(([label, value]) => <div key={label as string} className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{label as string}</p><p className={`mt-2 text-2xl font-black ${(value as number) < 0 ? "text-red-700" : "text-navy"}`}>{money(value as number)}</p></div>)}</div><section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">Banks & Wallet Balances</h2><p className="text-xs text-muted-foreground">Current balance of every bank and wallet account.</p></div><button onClick={() => setTab("accounts")} className="rounded border border-navy/15 px-3 py-2 text-xs font-bold text-navy">Manage accounts</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-2">Account</th><th className="p-2">Type</th><th className="p-2 text-right">Opening</th><th className="p-2 text-right">Current balance</th></tr></thead><tbody>{accounts.filter((account) => account.kind !== "cash").map((account) => <tr key={account.id} className="border-b border-navy/5"><td className="p-2 font-bold">{account.name}</td><td className="p-2 uppercase text-muted-foreground">{account.kind}</td><td className="p-2 text-right">{money(account.opening_balance)}</td><td className="p-2 text-right font-bold text-navy">{money(balance(account, transactions))}</td></tr>)}</tbody></table></div></section><section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">Recent activity</h2><p className="text-xs text-muted-foreground">The latest accounts-book entries.</p></div><button onClick={() => setShowEntry(true)} className="rounded bg-navy px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3 w-3" /> Add transaction</button></div><TransactionTable rows={recent} accounts={accounts} onDelete={(id) => deleteMutation.mutate(id)} onEdit={editEntry} /></section></>}
      {tab === "cashbook" && <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-black text-navy">Cash Book</h2><p className="mb-4 text-xs text-muted-foreground">Cash-in-hand opening balance, receipts, payments and running balance.</p><table className="w-full text-sm"><thead className="border-b text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-2">Date</th><th className="p-2">Description</th><th className="p-2 text-right">Received</th><th className="p-2 text-right">Payment</th><th className="p-2 text-right">Balance</th><th className="p-2" /></tr></thead><tbody>{cashRows.map((row) => { const incoming = row.direction === "in"; cashRunning += incoming ? Number(row.amount) : -Number(row.amount); return <tr key={row.id} className="border-b border-navy/5"><td className="p-2">{dateText(row.entry_date)}</td><td className="p-2">{row.description}</td><td className="p-2 text-right text-emerald-700">{incoming ? money(row.amount) : ""}</td><td className="p-2 text-right text-red-700">{incoming ? "" : money(row.amount)}</td><td className="p-2 text-right font-bold">{money(cashRunning)}</td><td className="p-2 text-right"><button type="button" onClick={() => editEntry(row)} className="mr-2 text-navy">Edit</button><button type="button" onClick={() => window.confirm("Delete this cash book entry?") && deleteMutation.mutate(row.id)} className="text-red-700"><Trash2 className="inline h-4 w-4" /></button></td></tr>; })}</tbody></table></section>}
      {tab === "sales" && <WorkflowList title="Sales Accounts" description="Booking sales linked to the selected cash or bank ledger." rows={filteredTransactions.filter((row) => row.entry_type === "sale")} accounts={accounts} actionLabel="Add Sale" onAdd={() => setWorkflow("sale")} onEdit={editEntry} onDelete={(row) => row.source_id && linkedDeleteMutation.mutate({ source_type: "sale", source_id: row.source_id })} />}
      {tab === "expenses" && <WorkflowList title="Expenses" description="Personal and office expenses linked to their payment source." rows={filteredTransactions.filter((row) => row.entry_type === "expense")} accounts={accounts} actionLabel="Add Expense" onAdd={() => setWorkflow("expense")} onEdit={editEntry} onDelete={(row) => row.source_id && linkedDeleteMutation.mutate({ source_type: "expense", source_id: row.source_id })} />}
      {tab === "accounts" && <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">Banks & Wallet</h2><p className="text-xs text-muted-foreground">Edit opening balances, opening dates, and current balances.</p></div><button onClick={() => setShowAccount(true)} className="rounded bg-navy px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3 w-3" /> Add account</button></div><table className="w-full text-sm"><thead className="border-b text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-2">Account</th><th className="p-2">Type</th><th className="p-2">Opening balance</th><th className="p-2">Opening date</th><th className="p-2 text-right">Current balance</th><th className="p-2" /></tr></thead><tbody>{accounts.map((account) => <tr key={account.id} className="border-b border-navy/5"><td className="p-2 font-bold">{account.name}</td><td className="p-2 uppercase text-muted-foreground">{account.kind}</td><td className="p-2"><div className="flex gap-2"><input className="w-36 rounded border px-2 py-1" type="number" defaultValue={account.opening_balance} onBlur={(event) => openingMutation.mutate({ id: account.id, opening_balance: Number(event.target.value) || 0, opening_balance_date: account.opening_balance_date })} /><Save className="mt-1 h-4 w-4 text-gold" /></div></td><td className="p-2"><input className="rounded border px-2 py-1" type="date" defaultValue={account.opening_balance_date ?? new Date().toISOString().slice(0, 10)} onBlur={(event) => openingMutation.mutate({ id: account.id, opening_balance: Number(account.opening_balance) || 0, opening_balance_date: event.target.value })} /></td><td className="p-2 text-right font-bold">{money(balance(account, transactions))}</td><td className="p-2 text-right"><button type="button" onClick={() => window.confirm(`Deactivate ${account.name}?`) && accountDeleteMutation.mutate(account.id)} className="text-red-700" title="Delete account"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></section>}
      {tab === "accounts" && selectedAccount && <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">{selectedAccount.name} Ledger</h2><p className="text-xs text-muted-foreground">Separate ledger for this bank or wallet, with running balance.</p></div><button onClick={() => setWorkflow("transfer")} className="rounded bg-gold px-3 py-2 text-xs font-bold text-navy"><Plus className="mr-1 inline h-3 w-3" /> Transfer To</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-2">Date</th><th className="p-2">Description</th><th className="p-2 text-right">In</th><th className="p-2 text-right">Out</th><th className="p-2 text-right">Balance</th><th className="p-2" /></tr></thead><tbody>{(() => { let running = Number(selectedAccount.opening_balance || 0); return selectedAccountRows.map((row) => { const incoming = row.direction === "in"; running += incoming ? Number(row.amount) : -Number(row.amount); return <tr key={row.id} className="border-b border-navy/5"><td className="p-2">{dateText(row.entry_date)}</td><td className="p-2">{row.description}</td><td className="p-2 text-right text-emerald-700">{incoming ? money(row.amount) : ""}</td><td className="p-2 text-right text-red-700">{incoming ? "" : money(row.amount)}</td><td className="p-2 text-right font-bold">{money(running)}</td><td className="p-2 text-right"><button type="button" onClick={() => editEntry(row)} className="mr-2 text-navy">Edit</button><button type="button" onClick={() => window.confirm("Delete this ledger entry?") && deleteMutation.mutate(row.id)} className="text-red-700"><Trash2 className="inline h-4 w-4" /></button></td></tr>; }); })()}</tbody></table></div></section>}
      {tab === "reports" && <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">Profit & loss</h2><p className="text-xs text-muted-foreground">Calculated from sales, purchases, and all expenses.</p></div><button onClick={() => printAccounts(accounts, filteredTransactions)} className="rounded bg-navy px-3 py-2 text-xs font-bold text-white"><FileText className="mr-1 inline h-3 w-3" /> Print report</button></div><div className="grid gap-3 md:grid-cols-4"><div className="rounded bg-emerald-50 p-4"><p className="text-xs">Sales</p><b>{money(totals.sales)}</b></div><div className="rounded bg-red-50 p-4"><p className="text-xs">Purchases</p><b>{money(totals.cost)}</b></div><div className="rounded bg-amber-50 p-4"><p className="text-xs">All Expenses</p><b>{money(totals.expenses)}</b></div><div className="rounded bg-navy p-4 text-white"><p className="text-xs">Net profit</p><b>{money(totals.sales - totals.cost - totals.expenses)}</b></div></div></section>}
      {tab === "settings" && <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-black text-navy">Settings</h2><p className="mb-4 text-xs text-muted-foreground">Manage services, vendors, airlines, and account defaults.</p><div className="grid gap-4 md:grid-cols-3"><div><h3 className="mb-2 font-bold text-navy">Services</h3><div className="space-y-2">{services.map((service) => <div key={service.id} className="flex items-center gap-2"><span className="flex-1 rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-800">{service.name}</span><button type="button" onClick={() => { const name = window.prompt("Rename service", service.name); if (name) serviceUpdateMutation.mutate({ id: service.id, name }); }} className="text-xs text-navy">Edit</button><button type="button" onClick={() => serviceDeleteMutation.mutate(service.id)} className="text-xs text-red-700">Delete</button></div>)}</div><div className="mt-3 flex gap-2"><input className="min-w-0 flex-1 rounded border px-2 py-1 text-sm" placeholder="New service" value={newService} onChange={(event) => setNewService(event.target.value)} /><button type="button" onClick={() => newService.trim() && serviceCreateMutation.mutate({ name: newService.trim() })} className="rounded bg-navy px-3 py-1 text-xs font-bold text-white">Save</button></div></div><div><h3 className="mb-2 font-bold text-navy">Vendors</h3><div className="flex flex-wrap gap-2">{vendorNames.map((name) => <span key={name} className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{name}</span>)}</div></div><div><h3 className="mb-2 font-bold text-navy">Airlines with accounts</h3><div className="flex flex-wrap gap-2">{airlineNames.map((name) => <span key={name} className="rounded-full bg-sky-50 px-3 py-1 text-xs text-sky-800">{name}</span>)}</div></div></div></section>}
    </main>
    {showTransactionMenu && <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 className="font-serif text-xl font-black text-navy">Add Transaction</h2><p className="mt-1 text-sm text-muted-foreground">Choose the ledger workflow for this entry.</p><div className="mt-5 grid gap-2"><button onClick={() => { setShowTransactionMenu(false); setWorkflow("sale"); }} className="rounded bg-navy px-4 py-3 text-left text-sm font-bold text-white">Sale</button><button onClick={() => { setShowTransactionMenu(false); setWorkflow("expense"); }} className="rounded bg-navy px-4 py-3 text-left text-sm font-bold text-white">Expense</button><button onClick={() => { setShowTransactionMenu(false); setWorkflow("transfer"); }} className="rounded bg-navy px-4 py-3 text-left text-sm font-bold text-white">Transfer To</button><button onClick={() => { setShowTransactionMenu(false); setShowEntry(true); }} className="rounded border border-navy/15 px-4 py-3 text-left text-sm font-bold text-navy">Cash Book / Banks & Wallet manual entry</button></div><button onClick={() => setShowTransactionMenu(false)} className="mt-4 rounded border px-3 py-2 text-sm">Cancel</button></div></div>}
    {showEntry && <EntryDialog accounts={accounts} entry={entry} setEntry={setEntry} setEntryType={setEntryType} onClose={() => { if (!entry.description || window.confirm("Discard this ledger entry?")) { setShowEntry(false); setEditingTransaction(null); setEntry(emptyEntry()); } }} onSubmit={submitEntry} busy={entryMutation.isPending || editMutation.isPending} editing={Boolean(editingTransaction)} />}
    {workflow && <WorkflowDialog kind={workflow} accounts={accounts} onClose={() => setWorkflow(null)} onLinked={(data) => linkedMutation.mutate(data)} onTransfer={(data) => transferMutation.mutate(data)} busy={linkedMutation.isPending || transferMutation.isPending} />}
    {showAccount && <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><form onSubmit={(event) => { event.preventDefault(); accountMutation.mutate({ ...newAccount, opening_balance: Number(newAccount.opening_balance) || 0 }); }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 className="font-serif text-xl font-black text-navy">Add account</h2><input className="mt-4 w-full rounded border p-2" placeholder="Account name" value={newAccount.name} onChange={(event) => setNewAccount({ ...newAccount, name: event.target.value })} required /><select className="mt-3 w-full rounded border p-2" value={newAccount.kind} onChange={(event) => setNewAccount({ ...newAccount, kind: event.target.value as Account["kind"] })}><option value="bank">Bank</option><option value="wallet">Wallet</option><option value="cash">Cash in Hand</option></select><input className="mt-3 w-full rounded border p-2" type="number" placeholder="Opening balance" value={newAccount.opening_balance} onChange={(event) => setNewAccount({ ...newAccount, opening_balance: event.target.value })} /><label className="mt-3 block text-xs font-bold">Opening balance date<input className="mt-1 w-full rounded border p-2 font-normal" type="date" value={newAccount.opening_balance_date} onChange={(event) => setNewAccount({ ...newAccount, opening_balance_date: event.target.value })} /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setShowAccount(false)} className="rounded border px-3 py-2 text-sm">Cancel</button><button className="rounded bg-navy px-3 py-2 text-sm font-bold text-white">Save account</button></div></form></div>}
  </div>;
}

function WorkflowList({ title, description, rows, accounts, actionLabel, onAdd, onEdit, onDelete }: { title: string; description: string; rows: Transaction[]; accounts: Account[]; actionLabel: string; onAdd: () => void; onEdit: (row: Transaction) => void; onDelete: (row: Transaction) => void }) {
  return <section className="rounded-xl border border-navy/10 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-xl font-black text-navy">{title}</h2><p className="text-xs text-muted-foreground">{description}</p></div><button onClick={onAdd} className="rounded bg-gold px-3 py-2 text-xs font-bold text-navy"><Plus className="mr-1 inline h-3 w-3" /> {actionLabel}</button></div><TransactionTable rows={[...rows].sort((a, b) => b.entry_date.localeCompare(a.entry_date))} accounts={accounts} onEdit={onEdit} onDelete={(id) => { const row = rows.find((item) => item.id === id); if (row) onDelete(row); }} /></section>;
}

function WorkflowDialog({ kind, accounts, onClose, onLinked, onTransfer, busy }: { kind: "sale" | "expense" | "transfer"; accounts: Account[]; onClose: () => void; onLinked: (data: any) => void; onTransfer: (data: any) => void; busy: boolean }) {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [category, setCategory] = useState(kind === "expense" ? expenseCategories[0] : salesCategories[0]);
  const [description, setDescription] = useState("");
  const [party, setParty] = useState("");
  const [amount, setAmount] = useState("");
  const [cost, setCost] = useState("0");
  const [accountId, setAccountId] = useState(accounts[0]?.id ?? "");
  const [fromId, setFromId] = useState(accounts[0]?.id ?? "");
  const [toId, setToId] = useState(accounts[1]?.id ?? accounts[0]?.id ?? "");
  const sourceId = crypto.randomUUID();
  const submit = (event: React.FormEvent) => { event.preventDefault(); const numericAmount = Number(amount); if (!description || numericAmount <= 0) { toast.error("Enter a description and amount greater than zero"); return; } if (kind === "transfer") { if (fromId === toId) { toast.error("Choose different source and destination accounts"); return; } onTransfer({ entry_date: date, category: "Transfer", description, from_account_id: fromId, to_account_id: toId, amount: numericAmount, source_id: sourceId }); return; } onLinked({ entry_date: date, category, party: party || undefined, description, account_id: accountId, amount: numericAmount, direct_cost: kind === "sale" ? Number(cost) || 0 : 0, source_id: sourceId, source_type: kind }); };
  const categoryOptions = kind === "expense" ? expenseCategories : salesCategories;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><h2 className="font-serif text-xl font-black text-navy">{kind === "transfer" ? "Transfer To" : kind === "sale" ? "Add Sale" : "Add Expense"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Date<input className="mt-1 w-full rounded border p-2 font-normal" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label>{kind === "transfer" ? <><label className="text-xs font-bold">From<select className="mt-1 w-full rounded border p-2 font-normal" value={fromId} onChange={(event) => setFromId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-xs font-bold">To<select className="mt-1 w-full rounded border p-2 font-normal" value={toId} onChange={(event) => setToId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></> : <><label className="text-xs font-bold">Category<select className="mt-1 w-full rounded border p-2 font-normal" value={category} onChange={(event) => setCategory(event.target.value)}>{categoryOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">In Account<select className="mt-1 w-full rounded border p-2 font-normal" value={accountId} onChange={(event) => setAccountId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></>}</div>{kind === "sale" && <label className="mt-3 block text-xs font-bold">Pax name<input className="mt-1 w-full rounded border p-2 font-normal" value={party} onChange={(event) => setParty(event.target.value)} /></label>}<label className="mt-3 block text-xs font-bold">Description<input className="mt-1 w-full rounded border p-2 font-normal" value={description} onChange={(event) => setDescription(event.target.value)} required /></label><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">{kind === "expense" ? "Expense Amount" : "Sale Amount"}<input className="mt-1 w-full rounded border p-2 font-normal" type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label>{kind === "sale" && <label className="text-xs font-bold">Purchase<input className="mt-1 w-full rounded border p-2 font-normal" type="number" min="0" value={cost} onChange={(event) => setCost(event.target.value)} /></label>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-3 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded bg-navy px-3 py-2 text-sm font-bold text-white">{busy ? "Saving..." : "Save"}</button></div></form></div>;
}

function EntryDialog({ accounts, entry, setEntry, setEntryType, onClose, onSubmit, busy, editing }: { accounts: Account[]; entry: any; setEntry: (value: any) => void; setEntryType: (value: string) => void; onClose: () => void; onSubmit: (event: React.FormEvent) => void; busy: boolean; editing: boolean }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4"><form onSubmit={onSubmit} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><h2 className="font-serif text-xl font-black text-navy">Add transaction</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Type<select className="mt-1 w-full rounded border p-2 font-normal" value={entry.entry_type} onChange={(event) => setEntryType(event.target.value)}><option value="sale">Sale</option><option value="expense">Expense</option><option value="transfer">Transfer</option><option value="manual">Manual</option></select></label><label className="text-xs font-bold">Date<input className="mt-1 w-full rounded border p-2 font-normal" type="date" value={entry.entry_date} onChange={(event) => setEntry({ ...entry, entry_date: event.target.value })} /></label><label className="text-xs font-bold">Account<select className="mt-1 w-full rounded border p-2 font-normal" value={entry.account_id} onChange={(event) => setEntry({ ...entry, account_id: event.target.value })}><option value="">Choose account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-xs font-bold">Category<input className="mt-1 w-full rounded border p-2 font-normal" value={entry.category} onChange={(event) => setEntry({ ...entry, category: event.target.value })} /></label></div><label className="mt-3 block text-xs font-bold">Party / customer<input className="mt-1 w-full rounded border p-2 font-normal" value={entry.party} onChange={(event) => setEntry({ ...entry, party: event.target.value })} /></label><label className="mt-3 block text-xs font-bold">Description<input className="mt-1 w-full rounded border p-2 font-normal" value={entry.description} onChange={(event) => setEntry({ ...entry, description: event.target.value })} required /></label><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Amount<input className="mt-1 w-full rounded border p-2 font-normal" type="number" min="1" value={entry.amount} onChange={(event) => setEntry({ ...entry, amount: event.target.value })} required /></label><label className="text-xs font-bold">Direct cost<input className="mt-1 w-full rounded border p-2 font-normal" type="number" min="0" value={entry.direct_cost} onChange={(event) => setEntry({ ...entry, direct_cost: event.target.value })} /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-3 py-2 text-sm">Cancel</button><button className="rounded bg-gold px-3 py-2 text-sm font-bold text-navy" disabled={busy}>{busy ? "Saving…" : "Save transaction"}</button></div></form></div>;
}

function TransactionTable({ rows, accounts, onEdit, onDelete }: { rows: Transaction[]; accounts: Account[]; onEdit?: (row: Transaction) => void; onDelete: (id: string) => void }) {
  const names = new Map(accounts.map((account) => [account.id, account.name]));
  return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-2">Date</th><th className="p-2">Source</th><th className="p-2">Pax / Description</th><th className="p-2">In Account</th><th className="p-2 text-right">Sale / Expense</th><th className="p-2 text-right">Purchase</th><th className="p-2" /></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-navy/5"><td className="p-2">{dateText(row.entry_date)}</td><td className="p-2 uppercase text-muted-foreground">{row.entry_type}</td><td className="p-2"><b>{row.party || row.category}</b><br /><span className="text-xs text-muted-foreground">{row.description}</span></td><td className="p-2">{names.get(row.account_id)}</td><td className={`p-2 text-right font-bold ${row.direction === "in" ? "text-emerald-700" : "text-red-700"}`}>{row.direction === "out" ? "-" : "+"}{money(row.amount)}</td><td className="p-2 text-right">{row.entry_type === "sale" ? money(row.direct_cost) : ""}</td><td className="p-2 text-right"><div className="flex justify-end gap-2"><button type="button" onClick={() => onEdit?.(row)} className="text-navy" title="Edit transaction">Edit</button><button type="button" onClick={() => window.confirm("Delete this transaction? This cannot be undone.") && onDelete(row.id)} className="text-red-700" title="Delete transaction"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>;
}
