const C = { clay: '#D97757', ink: '#141413', paper: '#FAF9F5', linen: '#F4EFEA', charcoal: '#1C1917', muted: '#78716C', border: '#E7E5E4', white: '#FFFFFF' } as const

export function escapeEmailHtml(value: unknown) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character)
}

export function emailRows(rows: Array<[string, unknown]>) {
  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:18px 0;border-collapse:collapse;border:1px solid ${C.border}"><tbody>${rows.map(([label, value], index) => `<tr style="background:${index % 2 ? C.paper : C.white}"><td style="width:38%;padding:10px 12px;border-bottom:1px solid ${C.border};color:${C.muted};font-size:12px;line-height:18px;vertical-align:top">${escapeEmailHtml(label)}</td><td style="padding:10px 12px;border-bottom:1px solid ${C.border};color:${C.charcoal};font-size:13px;line-height:19px;font-weight:600;vertical-align:top;white-space:pre-line">${escapeEmailHtml(value)}</td></tr>`).join('')}</tbody></table>`
}

export function brandedEmailHtml(input: { preview?: string; category: string; title: string; intro?: string; body?: string; action?: { label: string; url: string }; secondaryAction?: { label: string; url: string } }) {
  const action = input.action ? `<a class="rohi-button" href="${escapeEmailHtml(input.action.url)}" style="display:inline-block;min-height:44px;box-sizing:border-box;padding:13px 22px;border-radius:6px;background:${C.ink};color:${C.white};font-size:14px;line-height:18px;font-weight:700;text-decoration:none">${escapeEmailHtml(input.action.label)}</a>` : ''
  const secondary = input.secondaryAction ? `<a class="rohi-button" href="${escapeEmailHtml(input.secondaryAction.url)}" style="display:inline-block;min-height:44px;box-sizing:border-box;margin-left:8px;padding:12px 22px;border-radius:6px;border:1.5px solid ${C.ink};background:${C.paper};color:${C.ink};font-size:14px;line-height:18px;font-weight:700;text-decoration:none">${escapeEmailHtml(input.secondaryAction.label)}</a>` : ''
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeEmailHtml(input.preview ?? input.title)}</title><style>@media screen and (max-width:600px){.rohi-shell{width:100%!important}.rohi-content{padding:24px 20px!important}.rohi-header,.rohi-footer{padding-left:20px!important;padding-right:20px!important}.rohi-button{display:block!important;width:100%!important;text-align:center!important;margin:8px 0!important}}</style></head><body style="margin:0;padding:24px 10px;background:${C.linen};font-family:Arial,Helvetica,sans-serif"><table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr><td align="center"><table role="presentation" cellpadding="0" cellspacing="0" width="600" class="rohi-shell" style="width:100%;max-width:600px;background:${C.paper};border:1px solid ${C.border}"><tr><td class="rohi-header" style="padding:24px 32px;background:${C.clay};color:${C.white}"><div style="font-size:17px;line-height:24px;font-weight:700">ROHI INTERNATIONAL TRAVELS</div><div style="margin-top:4px;font-size:12px;line-height:18px">${escapeEmailHtml(input.category)}</div></td></tr><tr><td class="rohi-content" style="padding:32px;background:${C.paper};color:${C.charcoal}"><h1 style="margin:0 0 14px;color:${C.ink};font-size:26px;line-height:34px">${escapeEmailHtml(input.title)}</h1>${input.intro ? `<p style="margin:0 0 16px;font-size:15px;line-height:24px">${input.intro}</p>` : ''}${input.body ?? ''}${action}${secondary}</td></tr><tr><td class="rohi-footer" style="padding:24px 32px;background:${C.ink};color:${C.white}"><div style="margin-bottom:8px;font-size:13px;line-height:20px;font-weight:700">ROHI INTERNATIONAL TRAVELS</div><div style="font-size:11px;line-height:18px">Support: <a href="tel:+923056622988" style="color:${C.white}">+92 305 6622988</a> · <a href="mailto:rohitravelsryk@gmail.com" style="color:${C.white}">rohitravelsryk@gmail.com</a></div><div style="margin-top:4px;font-size:11px;line-height:18px"><a href="https://www.rohitravels.com" style="color:${C.white}">Website</a> · <a href="https://www.facebook.com/rohitravelsryk" style="color:${C.white}">Facebook</a> · <a href="https://www.instagram.com/rohitravels/" style="color:${C.white}">Instagram</a> · <a href="https://wa.me/923056622988" style="color:${C.white}">WhatsApp</a></div></td></tr></table></td></tr></table></body></html>`
}

export function otpEmailBlock(code: string, expiry: string) {
  return `<div style="margin:18px 0;padding:18px;border:1px solid ${C.border};border-left:4px solid ${C.clay};background:${C.white};color:${C.ink};font-family:'Courier New',monospace;font-size:32px;line-height:38px;font-weight:700;text-align:center;letter-spacing:6px">${escapeEmailHtml(code)}</div><p style="margin:0 0 16px;color:${C.muted};font-size:12px;line-height:19px">${escapeEmailHtml(expiry)}</p>`
}