/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyVisaRouteImport } from './routes/verify-visa'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrintFormatRouteImport } from './routes/print-format'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LatestUpdatesRouteImport } from './routes/latest-updates'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as DiscountvouchersRouteImport } from './routes/discountvouchers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentappRouteImport } from './routes/_agentapp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PreviewTiltCardsRouteImport } from './routes/preview.tilt-cards'
import { Route as PreviewStorySearchRouteImport } from './routes/preview.story-search'
import { Route as PreviewStickySearchRouteImport } from './routes/preview.sticky-search'
import { Route as PreviewSplitFlapRouteImport } from './routes/preview.split-flap'
import { Route as PreviewScrollStoryRouteImport } from './routes/preview.scroll-story'
import { Route as PreviewRouteLineRouteImport } from './routes/preview.route-line'
import { Route as PreviewParallaxHeroRouteImport } from './routes/preview.parallax-hero'
import { Route as PreviewKineticTypeRouteImport } from './routes/preview.kinetic-type'
import { Route as PreviewDarkLuxeRouteImport } from './routes/preview.dark-luxe'
import { Route as PreviewBentoRouteImport } from './routes/preview.bento'
import { Route as PreviewAuroraRouteImport } from './routes/preview.aurora'
import { Route as AgentRegisterRouteImport } from './routes/agent.register'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminVisaLinksRouteImport } from './routes/admin.visa-links'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminStickyNotesRouteImport } from './routes/admin.sticky-notes'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSelfGroupsRouteImport } from './routes/admin.self-groups'
import { Route as AdminQueriesRouteImport } from './routes/admin.queries'
import { Route as AdminOkToBoardRouteImport } from './routes/admin.ok-to-board'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminLatestUpdatesRouteImport } from './routes/admin.latest-updates'
import { Route as AdminGroupTicketFormatRouteImport } from './routes/admin.group-ticket-format'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAnnouncementBannerRouteImport } from './routes/admin.announcement-banner'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicAgentApproveRouteImport } from './routes/api/public/agent-approve'
import { Route as AdminMarketingEmailRouteImport } from './routes/admin/marketing/email'
import { Route as AgentappAgentStickyNotesRouteImport } from './routes/_agentapp.agent.sticky-notes'
import { Route as AgentappAgentProfileRouteImport } from './routes/_agentapp.agent.profile'
import { Route as AgentappAgentLedgerRouteImport } from './routes/_agentapp.agent.ledger'
import { Route as AgentappAgentFaresRouteImport } from './routes/_agentapp.agent.fares'
import { Route as AgentappAgentDashboardRouteImport } from './routes/_agentapp.agent.dashboard'
import { Route as AgentappAgentChangePasswordRouteImport } from './routes/_agentapp.agent.change-password'
import { Route as AgentappAgentBookingsRouteImport } from './routes/_agentapp.agent.bookings'
import { Route as AgentappAgentAdminRouteImport } from './routes/_agentapp.agent.admin'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksTicketRemindersRouteImport } from './routes/api/public/hooks/ticket-reminders'
import { Route as ApiPublicHooksBackupSyncRouteImport } from './routes/api/public/hooks/backup-sync'

const VerifyVisaRoute = VerifyVisaRouteImport.update({
  id: '/verify-visa',
  path: '/verify-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintFormatRoute = PrintFormatRouteImport.update({
  id: '/print-format',
  path: '/print-format',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestUpdatesRoute = LatestUpdatesRouteImport.update({
  id: '/latest-updates',
  path: '/latest-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountvouchersRoute = DiscountvouchersRouteImport.update({
  id: '/discountvouchers',
  path: '/discountvouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentappRoute = AgentappRouteImport.update({
  id: '/_agentapp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PreviewTiltCardsRoute = PreviewTiltCardsRouteImport.update({
  id: '/preview/tilt-cards',
  path: '/preview/tilt-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewStorySearchRoute = PreviewStorySearchRouteImport.update({
  id: '/preview/story-search',
  path: '/preview/story-search',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewStickySearchRoute = PreviewStickySearchRouteImport.update({
  id: '/preview/sticky-search',
  path: '/preview/sticky-search',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSplitFlapRoute = PreviewSplitFlapRouteImport.update({
  id: '/preview/split-flap',
  path: '/preview/split-flap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewScrollStoryRoute = PreviewScrollStoryRouteImport.update({
  id: '/preview/scroll-story',
  path: '/preview/scroll-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRouteLineRoute = PreviewRouteLineRouteImport.update({
  id: '/preview/route-line',
  path: '/preview/route-line',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewParallaxHeroRoute = PreviewParallaxHeroRouteImport.update({
  id: '/preview/parallax-hero',
  path: '/preview/parallax-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKineticTypeRoute = PreviewKineticTypeRouteImport.update({
  id: '/preview/kinetic-type',
  path: '/preview/kinetic-type',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDarkLuxeRoute = PreviewDarkLuxeRouteImport.update({
  id: '/preview/dark-luxe',
  path: '/preview/dark-luxe',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewBentoRoute = PreviewBentoRouteImport.update({
  id: '/preview/bento',
  path: '/preview/bento',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAuroraRoute = PreviewAuroraRouteImport.update({
  id: '/preview/aurora',
  path: '/preview/aurora',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRegisterRoute = AgentRegisterRouteImport.update({
  id: '/agent/register',
  path: '/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisaLinksRoute = AdminVisaLinksRouteImport.update({
  id: '/visa-links',
  path: '/visa-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStickyNotesRoute = AdminStickyNotesRouteImport.update({
  id: '/sticky-notes',
  path: '/sticky-notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSelfGroupsRoute = AdminSelfGroupsRouteImport.update({
  id: '/self-groups',
  path: '/self-groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOkToBoardRoute = AdminOkToBoardRouteImport.update({
  id: '/ok-to-board',
  path: '/ok-to-board',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLatestUpdatesRoute = AdminLatestUpdatesRouteImport.update({
  id: '/latest-updates',
  path: '/latest-updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupTicketFormatRoute = AdminGroupTicketFormatRouteImport.update({
  id: '/group-ticket-format',
  path: '/group-ticket-format',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementBannerRoute = AdminAnnouncementBannerRouteImport.update({
  id: '/announcement-banner',
  path: '/announcement-banner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentApproveRoute = ApiPublicAgentApproveRouteImport.update({
  id: '/api/public/agent-approve',
  path: '/api/public/agent-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingEmailRoute = AdminMarketingEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AgentappAgentStickyNotesRoute =
  AgentappAgentStickyNotesRouteImport.update({
    id: '/agent/sticky-notes',
    path: '/agent/sticky-notes',
    getParentRoute: () => AgentappRoute,
  } as any)
const AgentappAgentProfileRoute = AgentappAgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentLedgerRoute = AgentappAgentLedgerRouteImport.update({
  id: '/agent/ledger',
  path: '/agent/ledger',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentFaresRoute = AgentappAgentFaresRouteImport.update({
  id: '/agent/fares',
  path: '/agent/fares',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentDashboardRoute = AgentappAgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentChangePasswordRoute =
  AgentappAgentChangePasswordRouteImport.update({
    id: '/agent/change-password',
    path: '/agent/change-password',
    getParentRoute: () => AgentappRoute,
  } as any)
const AgentappAgentBookingsRoute = AgentappAgentBookingsRouteImport.update({
  id: '/agent/bookings',
  path: '/agent/bookings',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentAdminRoute = AgentappAgentAdminRouteImport.update({
  id: '/agent/admin',
  path: '/agent/admin',
  getParentRoute: () => AgentappRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTicketRemindersRoute =
  ApiPublicHooksTicketRemindersRouteImport.update({
    id: '/api/public/hooks/ticket-reminders',
    path: '/api/public/hooks/ticket-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackupSyncRoute =
  ApiPublicHooksBackupSyncRouteImport.update({
    id: '/api/public/hooks/backup-sync',
    path: '/api/public/hooks/backup-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/latest-updates': typeof LatestUpdatesRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement-banner': typeof AdminAnnouncementBannerRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/latest-updates': typeof AdminLatestUpdatesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sticky-notes': typeof AdminStickyNotesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/preview/aurora': typeof PreviewAuroraRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark-luxe': typeof PreviewDarkLuxeRoute
  '/preview/kinetic-type': typeof PreviewKineticTypeRoute
  '/preview/parallax-hero': typeof PreviewParallaxHeroRoute
  '/preview/route-line': typeof PreviewRouteLineRoute
  '/preview/scroll-story': typeof PreviewScrollStoryRoute
  '/preview/split-flap': typeof PreviewSplitFlapRoute
  '/preview/sticky-search': typeof PreviewStickySearchRoute
  '/preview/story-search': typeof PreviewStorySearchRoute
  '/preview/tilt-cards': typeof PreviewTiltCardsRoute
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agent/admin': typeof AgentappAgentAdminRoute
  '/agent/bookings': typeof AgentappAgentBookingsRoute
  '/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/agent/fares': typeof AgentappAgentFaresRoute
  '/agent/ledger': typeof AgentappAgentLedgerRoute
  '/agent/profile': typeof AgentappAgentProfileRoute
  '/agent/sticky-notes': typeof AgentappAgentStickyNotesRoute
  '/admin/marketing/email': typeof AdminMarketingEmailRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/backup-sync': typeof ApiPublicHooksBackupSyncRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/latest-updates': typeof LatestUpdatesRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement-banner': typeof AdminAnnouncementBannerRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/latest-updates': typeof AdminLatestUpdatesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sticky-notes': typeof AdminStickyNotesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/preview/aurora': typeof PreviewAuroraRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark-luxe': typeof PreviewDarkLuxeRoute
  '/preview/kinetic-type': typeof PreviewKineticTypeRoute
  '/preview/parallax-hero': typeof PreviewParallaxHeroRoute
  '/preview/route-line': typeof PreviewRouteLineRoute
  '/preview/scroll-story': typeof PreviewScrollStoryRoute
  '/preview/split-flap': typeof PreviewSplitFlapRoute
  '/preview/sticky-search': typeof PreviewStickySearchRoute
  '/preview/story-search': typeof PreviewStorySearchRoute
  '/preview/tilt-cards': typeof PreviewTiltCardsRoute
  '/admin': typeof AdminIndexRoute
  '/preview': typeof PreviewIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agent/admin': typeof AgentappAgentAdminRoute
  '/agent/bookings': typeof AgentappAgentBookingsRoute
  '/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/agent/fares': typeof AgentappAgentFaresRoute
  '/agent/ledger': typeof AgentappAgentLedgerRoute
  '/agent/profile': typeof AgentappAgentProfileRoute
  '/agent/sticky-notes': typeof AgentappAgentStickyNotesRoute
  '/admin/marketing/email': typeof AdminMarketingEmailRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/backup-sync': typeof ApiPublicHooksBackupSyncRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_agentapp': typeof AgentappRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/latest-updates': typeof LatestUpdatesRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement-banner': typeof AdminAnnouncementBannerRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/latest-updates': typeof AdminLatestUpdatesRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sticky-notes': typeof AdminStickyNotesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/preview/aurora': typeof PreviewAuroraRoute
  '/preview/bento': typeof PreviewBentoRoute
  '/preview/dark-luxe': typeof PreviewDarkLuxeRoute
  '/preview/kinetic-type': typeof PreviewKineticTypeRoute
  '/preview/parallax-hero': typeof PreviewParallaxHeroRoute
  '/preview/route-line': typeof PreviewRouteLineRoute
  '/preview/scroll-story': typeof PreviewScrollStoryRoute
  '/preview/split-flap': typeof PreviewSplitFlapRoute
  '/preview/sticky-search': typeof PreviewStickySearchRoute
  '/preview/story-search': typeof PreviewStorySearchRoute
  '/preview/tilt-cards': typeof PreviewTiltCardsRoute
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_agentapp/agent/admin': typeof AgentappAgentAdminRoute
  '/_agentapp/agent/bookings': typeof AgentappAgentBookingsRoute
  '/_agentapp/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/_agentapp/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/_agentapp/agent/fares': typeof AgentappAgentFaresRoute
  '/_agentapp/agent/ledger': typeof AgentappAgentLedgerRoute
  '/_agentapp/agent/profile': typeof AgentappAgentProfileRoute
  '/_agentapp/agent/sticky-notes': typeof AgentappAgentStickyNotesRoute
  '/admin/marketing/email': typeof AdminMarketingEmailRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/backup-sync': typeof ApiPublicHooksBackupSyncRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/latest-updates'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/theme-preview'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement-banner'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/group-ticket-format'
    | '/admin/latest-updates'
    | '/admin/ledger'
    | '/admin/marketing'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/staff'
    | '/admin/sticky-notes'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/preview/aurora'
    | '/preview/bento'
    | '/preview/dark-luxe'
    | '/preview/kinetic-type'
    | '/preview/parallax-hero'
    | '/preview/route-line'
    | '/preview/scroll-story'
    | '/preview/split-flap'
    | '/preview/sticky-search'
    | '/preview/story-search'
    | '/preview/tilt-cards'
    | '/admin/'
    | '/preview/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agent/admin'
    | '/agent/bookings'
    | '/agent/change-password'
    | '/agent/dashboard'
    | '/agent/fares'
    | '/agent/ledger'
    | '/agent/profile'
    | '/agent/sticky-notes'
    | '/admin/marketing/email'
    | '/api/public/agent-approve'
    | '/api/public/hooks/backup-sync'
    | '/api/public/hooks/ticket-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/latest-updates'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/theme-preview'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement-banner'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/group-ticket-format'
    | '/admin/latest-updates'
    | '/admin/ledger'
    | '/admin/marketing'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/staff'
    | '/admin/sticky-notes'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/preview/aurora'
    | '/preview/bento'
    | '/preview/dark-luxe'
    | '/preview/kinetic-type'
    | '/preview/parallax-hero'
    | '/preview/route-line'
    | '/preview/scroll-story'
    | '/preview/split-flap'
    | '/preview/sticky-search'
    | '/preview/story-search'
    | '/preview/tilt-cards'
    | '/admin'
    | '/preview'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agent/admin'
    | '/agent/bookings'
    | '/agent/change-password'
    | '/agent/dashboard'
    | '/agent/fares'
    | '/agent/ledger'
    | '/agent/profile'
    | '/agent/sticky-notes'
    | '/admin/marketing/email'
    | '/api/public/agent-approve'
    | '/api/public/hooks/backup-sync'
    | '/api/public/hooks/ticket-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_agentapp'
    | '/admin'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/latest-updates'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/theme-preview'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement-banner'
    | '/admin/backup'
    | '/admin/bookings'
    | '/admin/group-ticket-format'
    | '/admin/latest-updates'
    | '/admin/ledger'
    | '/admin/marketing'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/staff'
    | '/admin/sticky-notes'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/preview/aurora'
    | '/preview/bento'
    | '/preview/dark-luxe'
    | '/preview/kinetic-type'
    | '/preview/parallax-hero'
    | '/preview/route-line'
    | '/preview/scroll-story'
    | '/preview/split-flap'
    | '/preview/sticky-search'
    | '/preview/story-search'
    | '/preview/tilt-cards'
    | '/admin/'
    | '/preview/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_agentapp/agent/admin'
    | '/_agentapp/agent/bookings'
    | '/_agentapp/agent/change-password'
    | '/_agentapp/agent/dashboard'
    | '/_agentapp/agent/fares'
    | '/_agentapp/agent/ledger'
    | '/_agentapp/agent/profile'
    | '/_agentapp/agent/sticky-notes'
    | '/admin/marketing/email'
    | '/api/public/agent-approve'
    | '/api/public/hooks/backup-sync'
    | '/api/public/hooks/ticket-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentappRoute: typeof AgentappRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  DiscountvouchersRoute: typeof DiscountvouchersRoute
  InquiryRoute: typeof InquiryRoute
  LatestUpdatesRoute: typeof LatestUpdatesRoute
  McpRoute: typeof McpRoute
  PrintFormatRoute: typeof PrintFormatRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  VerifyVisaRoute: typeof VerifyVisaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentRegisterRoute: typeof AgentRegisterRoute
  PreviewAuroraRoute: typeof PreviewAuroraRoute
  PreviewBentoRoute: typeof PreviewBentoRoute
  PreviewDarkLuxeRoute: typeof PreviewDarkLuxeRoute
  PreviewKineticTypeRoute: typeof PreviewKineticTypeRoute
  PreviewParallaxHeroRoute: typeof PreviewParallaxHeroRoute
  PreviewRouteLineRoute: typeof PreviewRouteLineRoute
  PreviewScrollStoryRoute: typeof PreviewScrollStoryRoute
  PreviewSplitFlapRoute: typeof PreviewSplitFlapRoute
  PreviewStickySearchRoute: typeof PreviewStickySearchRoute
  PreviewStorySearchRoute: typeof PreviewStorySearchRoute
  PreviewTiltCardsRoute: typeof PreviewTiltCardsRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAgentApproveRoute: typeof ApiPublicAgentApproveRoute
  ApiPublicHooksBackupSyncRoute: typeof ApiPublicHooksBackupSyncRoute
  ApiPublicHooksTicketRemindersRoute: typeof ApiPublicHooksTicketRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-visa': {
      id: '/verify-visa'
      path: '/verify-visa'
      fullPath: '/verify-visa'
      preLoaderRoute: typeof VerifyVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-format': {
      id: '/print-format'
      path: '/print-format'
      fullPath: '/print-format'
      preLoaderRoute: typeof PrintFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-updates': {
      id: '/latest-updates'
      path: '/latest-updates'
      fullPath: '/latest-updates'
      preLoaderRoute: typeof LatestUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discountvouchers': {
      id: '/discountvouchers'
      path: '/discountvouchers'
      fullPath: '/discountvouchers'
      preLoaderRoute: typeof DiscountvouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agentapp': {
      id: '/_agentapp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preview/tilt-cards': {
      id: '/preview/tilt-cards'
      path: '/preview/tilt-cards'
      fullPath: '/preview/tilt-cards'
      preLoaderRoute: typeof PreviewTiltCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/story-search': {
      id: '/preview/story-search'
      path: '/preview/story-search'
      fullPath: '/preview/story-search'
      preLoaderRoute: typeof PreviewStorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/sticky-search': {
      id: '/preview/sticky-search'
      path: '/preview/sticky-search'
      fullPath: '/preview/sticky-search'
      preLoaderRoute: typeof PreviewStickySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/split-flap': {
      id: '/preview/split-flap'
      path: '/preview/split-flap'
      fullPath: '/preview/split-flap'
      preLoaderRoute: typeof PreviewSplitFlapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/scroll-story': {
      id: '/preview/scroll-story'
      path: '/preview/scroll-story'
      fullPath: '/preview/scroll-story'
      preLoaderRoute: typeof PreviewScrollStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/route-line': {
      id: '/preview/route-line'
      path: '/preview/route-line'
      fullPath: '/preview/route-line'
      preLoaderRoute: typeof PreviewRouteLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/parallax-hero': {
      id: '/preview/parallax-hero'
      path: '/preview/parallax-hero'
      fullPath: '/preview/parallax-hero'
      preLoaderRoute: typeof PreviewParallaxHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/kinetic-type': {
      id: '/preview/kinetic-type'
      path: '/preview/kinetic-type'
      fullPath: '/preview/kinetic-type'
      preLoaderRoute: typeof PreviewKineticTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/dark-luxe': {
      id: '/preview/dark-luxe'
      path: '/preview/dark-luxe'
      fullPath: '/preview/dark-luxe'
      preLoaderRoute: typeof PreviewDarkLuxeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/bento': {
      id: '/preview/bento'
      path: '/preview/bento'
      fullPath: '/preview/bento'
      preLoaderRoute: typeof PreviewBentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/aurora': {
      id: '/preview/aurora'
      path: '/preview/aurora'
      fullPath: '/preview/aurora'
      preLoaderRoute: typeof PreviewAuroraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/register': {
      id: '/agent/register'
      path: '/agent/register'
      fullPath: '/agent/register'
      preLoaderRoute: typeof AgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visa-links': {
      id: '/admin/visa-links'
      path: '/visa-links'
      fullPath: '/admin/visa-links'
      preLoaderRoute: typeof AdminVisaLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sticky-notes': {
      id: '/admin/sticky-notes'
      path: '/sticky-notes'
      fullPath: '/admin/sticky-notes'
      preLoaderRoute: typeof AdminStickyNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/self-groups': {
      id: '/admin/self-groups'
      path: '/self-groups'
      fullPath: '/admin/self-groups'
      preLoaderRoute: typeof AdminSelfGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ok-to-board': {
      id: '/admin/ok-to-board'
      path: '/ok-to-board'
      fullPath: '/admin/ok-to-board'
      preLoaderRoute: typeof AdminOkToBoardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/latest-updates': {
      id: '/admin/latest-updates'
      path: '/latest-updates'
      fullPath: '/admin/latest-updates'
      preLoaderRoute: typeof AdminLatestUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/group-ticket-format': {
      id: '/admin/group-ticket-format'
      path: '/group-ticket-format'
      fullPath: '/admin/group-ticket-format'
      preLoaderRoute: typeof AdminGroupTicketFormatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcement-banner': {
      id: '/admin/announcement-banner'
      path: '/announcement-banner'
      fullPath: '/admin/announcement-banner'
      preLoaderRoute: typeof AdminAnnouncementBannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-approve': {
      id: '/api/public/agent-approve'
      path: '/api/public/agent-approve'
      fullPath: '/api/public/agent-approve'
      preLoaderRoute: typeof ApiPublicAgentApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing/email': {
      id: '/admin/marketing/email'
      path: '/email'
      fullPath: '/admin/marketing/email'
      preLoaderRoute: typeof AdminMarketingEmailRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/_agentapp/agent/sticky-notes': {
      id: '/_agentapp/agent/sticky-notes'
      path: '/agent/sticky-notes'
      fullPath: '/agent/sticky-notes'
      preLoaderRoute: typeof AgentappAgentStickyNotesRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/profile': {
      id: '/_agentapp/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentappAgentProfileRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/ledger': {
      id: '/_agentapp/agent/ledger'
      path: '/agent/ledger'
      fullPath: '/agent/ledger'
      preLoaderRoute: typeof AgentappAgentLedgerRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/fares': {
      id: '/_agentapp/agent/fares'
      path: '/agent/fares'
      fullPath: '/agent/fares'
      preLoaderRoute: typeof AgentappAgentFaresRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/dashboard': {
      id: '/_agentapp/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentappAgentDashboardRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/change-password': {
      id: '/_agentapp/agent/change-password'
      path: '/agent/change-password'
      fullPath: '/agent/change-password'
      preLoaderRoute: typeof AgentappAgentChangePasswordRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/bookings': {
      id: '/_agentapp/agent/bookings'
      path: '/agent/bookings'
      fullPath: '/agent/bookings'
      preLoaderRoute: typeof AgentappAgentBookingsRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/admin': {
      id: '/_agentapp/agent/admin'
      path: '/agent/admin'
      fullPath: '/agent/admin'
      preLoaderRoute: typeof AgentappAgentAdminRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ticket-reminders': {
      id: '/api/public/hooks/ticket-reminders'
      path: '/api/public/hooks/ticket-reminders'
      fullPath: '/api/public/hooks/ticket-reminders'
      preLoaderRoute: typeof ApiPublicHooksTicketRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup-sync': {
      id: '/api/public/hooks/backup-sync'
      path: '/api/public/hooks/backup-sync'
      fullPath: '/api/public/hooks/backup-sync'
      preLoaderRoute: typeof ApiPublicHooksBackupSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentappRouteChildren {
  AgentappAgentAdminRoute: typeof AgentappAgentAdminRoute
  AgentappAgentBookingsRoute: typeof AgentappAgentBookingsRoute
  AgentappAgentChangePasswordRoute: typeof AgentappAgentChangePasswordRoute
  AgentappAgentDashboardRoute: typeof AgentappAgentDashboardRoute
  AgentappAgentFaresRoute: typeof AgentappAgentFaresRoute
  AgentappAgentLedgerRoute: typeof AgentappAgentLedgerRoute
  AgentappAgentProfileRoute: typeof AgentappAgentProfileRoute
  AgentappAgentStickyNotesRoute: typeof AgentappAgentStickyNotesRoute
}

const AgentappRouteChildren: AgentappRouteChildren = {
  AgentappAgentAdminRoute: AgentappAgentAdminRoute,
  AgentappAgentBookingsRoute: AgentappAgentBookingsRoute,
  AgentappAgentChangePasswordRoute: AgentappAgentChangePasswordRoute,
  AgentappAgentDashboardRoute: AgentappAgentDashboardRoute,
  AgentappAgentFaresRoute: AgentappAgentFaresRoute,
  AgentappAgentLedgerRoute: AgentappAgentLedgerRoute,
  AgentappAgentProfileRoute: AgentappAgentProfileRoute,
  AgentappAgentStickyNotesRoute: AgentappAgentStickyNotesRoute,
}

const AgentappRouteWithChildren = AgentappRoute._addFileChildren(
  AgentappRouteChildren,
)

interface AdminMarketingRouteChildren {
  AdminMarketingEmailRoute: typeof AdminMarketingEmailRoute
}

const AdminMarketingRouteChildren: AdminMarketingRouteChildren = {
  AdminMarketingEmailRoute: AdminMarketingEmailRoute,
}

const AdminMarketingRouteWithChildren = AdminMarketingRoute._addFileChildren(
  AdminMarketingRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnnouncementBannerRoute: typeof AdminAnnouncementBannerRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminGroupTicketFormatRoute: typeof AdminGroupTicketFormatRoute
  AdminLatestUpdatesRoute: typeof AdminLatestUpdatesRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminMarketingRoute: typeof AdminMarketingRouteWithChildren
  AdminOkToBoardRoute: typeof AdminOkToBoardRoute
  AdminQueriesRoute: typeof AdminQueriesRoute
  AdminSelfGroupsRoute: typeof AdminSelfGroupsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStickyNotesRoute: typeof AdminStickyNotesRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminVisaLinksRoute: typeof AdminVisaLinksRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnnouncementBannerRoute: AdminAnnouncementBannerRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminGroupTicketFormatRoute: AdminGroupTicketFormatRoute,
  AdminLatestUpdatesRoute: AdminLatestUpdatesRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminMarketingRoute: AdminMarketingRouteWithChildren,
  AdminOkToBoardRoute: AdminOkToBoardRoute,
  AdminQueriesRoute: AdminQueriesRoute,
  AdminSelfGroupsRoute: AdminSelfGroupsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStickyNotesRoute: AdminStickyNotesRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminVisaLinksRoute: AdminVisaLinksRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentappRoute: AgentappRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  DiscountvouchersRoute: DiscountvouchersRoute,
  InquiryRoute: InquiryRoute,
  LatestUpdatesRoute: LatestUpdatesRoute,
  McpRoute: McpRoute,
  PrintFormatRoute: PrintFormatRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  VerifyVisaRoute: VerifyVisaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentRegisterRoute: AgentRegisterRoute,
  PreviewAuroraRoute: PreviewAuroraRoute,
  PreviewBentoRoute: PreviewBentoRoute,
  PreviewDarkLuxeRoute: PreviewDarkLuxeRoute,
  PreviewKineticTypeRoute: PreviewKineticTypeRoute,
  PreviewParallaxHeroRoute: PreviewParallaxHeroRoute,
  PreviewRouteLineRoute: PreviewRouteLineRoute,
  PreviewScrollStoryRoute: PreviewScrollStoryRoute,
  PreviewSplitFlapRoute: PreviewSplitFlapRoute,
  PreviewStickySearchRoute: PreviewStickySearchRoute,
  PreviewStorySearchRoute: PreviewStorySearchRoute,
  PreviewTiltCardsRoute: PreviewTiltCardsRoute,
  PreviewIndexRoute: PreviewIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAgentApproveRoute: ApiPublicAgentApproveRoute,
  ApiPublicHooksBackupSyncRoute: ApiPublicHooksBackupSyncRoute,
  ApiPublicHooksTicketRemindersRoute: ApiPublicHooksTicketRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
