/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyVisaRouteImport } from './routes/verify-visa'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrintFormatRouteImport } from './routes/print-format'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as DiscountvouchersRouteImport } from './routes/discountvouchers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentappRouteImport } from './routes/_agentapp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AgentRegisterRouteImport } from './routes/agent.register'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminVisaLinksRouteImport } from './routes/admin.visa-links'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminSelfGroupsRouteImport } from './routes/admin.self-groups'
import { Route as AdminQueriesRouteImport } from './routes/admin.queries'
import { Route as AdminOkToBoardRouteImport } from './routes/admin.ok-to-board'
import { Route as AdminGroupTicketFormatRouteImport } from './routes/admin.group-ticket-format'
import { Route as AdminAnnouncementRouteImport } from './routes/admin.announcement'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicAgentApproveRouteImport } from './routes/api/public/agent-approve'
import { Route as AgentappAgentProfileRouteImport } from './routes/_agentapp.agent.profile'
import { Route as AgentappAgentFaresRouteImport } from './routes/_agentapp.agent.fares'
import { Route as AgentappAgentDashboardRouteImport } from './routes/_agentapp.agent.dashboard'
import { Route as AgentappAgentChangePasswordRouteImport } from './routes/_agentapp.agent.change-password'
import { Route as AgentappAgentBookingsRouteImport } from './routes/_agentapp.agent.bookings'
import { Route as AgentappAgentAdminRouteImport } from './routes/_agentapp.agent.admin'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksTicketRemindersRouteImport } from './routes/api/public/hooks/ticket-reminders'

const VerifyVisaRoute = VerifyVisaRouteImport.update({
  id: '/verify-visa',
  path: '/verify-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintFormatRoute = PrintFormatRouteImport.update({
  id: '/print-format',
  path: '/print-format',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountvouchersRoute = DiscountvouchersRouteImport.update({
  id: '/discountvouchers',
  path: '/discountvouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentappRoute = AgentappRouteImport.update({
  id: '/_agentapp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRegisterRoute = AgentRegisterRouteImport.update({
  id: '/agent/register',
  path: '/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/admin/vouchers',
  path: '/admin/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisaLinksRoute = AdminVisaLinksRouteImport.update({
  id: '/admin/visa-links',
  path: '/admin/visa-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSelfGroupsRoute = AdminSelfGroupsRouteImport.update({
  id: '/admin/self-groups',
  path: '/admin/self-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/admin/queries',
  path: '/admin/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOkToBoardRoute = AdminOkToBoardRouteImport.update({
  id: '/admin/ok-to-board',
  path: '/admin/ok-to-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupTicketFormatRoute = AdminGroupTicketFormatRouteImport.update({
  id: '/admin/group-ticket-format',
  path: '/admin/group-ticket-format',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementRoute = AdminAnnouncementRouteImport.update({
  id: '/admin/announcement',
  path: '/admin/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentApproveRoute = ApiPublicAgentApproveRouteImport.update({
  id: '/api/public/agent-approve',
  path: '/api/public/agent-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentappAgentProfileRoute = AgentappAgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentFaresRoute = AgentappAgentFaresRouteImport.update({
  id: '/agent/fares',
  path: '/agent/fares',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentDashboardRoute = AgentappAgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentChangePasswordRoute =
  AgentappAgentChangePasswordRouteImport.update({
    id: '/agent/change-password',
    path: '/agent/change-password',
    getParentRoute: () => AgentappRoute,
  } as any)
const AgentappAgentBookingsRoute = AgentappAgentBookingsRouteImport.update({
  id: '/agent/bookings',
  path: '/agent/bookings',
  getParentRoute: () => AgentappRoute,
} as any)
const AgentappAgentAdminRoute = AgentappAgentAdminRouteImport.update({
  id: '/agent/admin',
  path: '/agent/admin',
  getParentRoute: () => AgentappRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTicketRemindersRoute =
  ApiPublicHooksTicketRemindersRouteImport.update({
    id: '/api/public/hooks/ticket-reminders',
    path: '/api/public/hooks/ticket-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agent/admin': typeof AgentappAgentAdminRoute
  '/agent/bookings': typeof AgentappAgentBookingsRoute
  '/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/agent/fares': typeof AgentappAgentFaresRoute
  '/agent/profile': typeof AgentappAgentProfileRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agent/admin': typeof AgentappAgentAdminRoute
  '/agent/bookings': typeof AgentappAgentBookingsRoute
  '/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/agent/fares': typeof AgentappAgentFaresRoute
  '/agent/profile': typeof AgentappAgentProfileRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_agentapp': typeof AgentappRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/discountvouchers': typeof DiscountvouchersRoute
  '/inquiry': typeof InquiryRoute
  '/mcp': typeof McpRoute
  '/print-format': typeof PrintFormatRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/verify-visa': typeof VerifyVisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/announcement': typeof AdminAnnouncementRoute
  '/admin/group-ticket-format': typeof AdminGroupTicketFormatRoute
  '/admin/ok-to-board': typeof AdminOkToBoardRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/self-groups': typeof AdminSelfGroupsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/visa-links': typeof AdminVisaLinksRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_agentapp/agent/admin': typeof AgentappAgentAdminRoute
  '/_agentapp/agent/bookings': typeof AgentappAgentBookingsRoute
  '/_agentapp/agent/change-password': typeof AgentappAgentChangePasswordRoute
  '/_agentapp/agent/dashboard': typeof AgentappAgentDashboardRoute
  '/_agentapp/agent/fares': typeof AgentappAgentFaresRoute
  '/_agentapp/agent/profile': typeof AgentappAgentProfileRoute
  '/api/public/agent-approve': typeof ApiPublicAgentApproveRoute
  '/api/public/hooks/ticket-reminders': typeof ApiPublicHooksTicketRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/templates'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement'
    | '/admin/group-ticket-format'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agent/admin'
    | '/agent/bookings'
    | '/agent/change-password'
    | '/agent/dashboard'
    | '/agent/fares'
    | '/agent/profile'
    | '/api/public/agent-approve'
    | '/api/public/hooks/ticket-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/templates'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement'
    | '/admin/group-ticket-format'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/agent/admin'
    | '/agent/bookings'
    | '/agent/change-password'
    | '/agent/dashboard'
    | '/agent/fares'
    | '/agent/profile'
    | '/api/public/agent-approve'
    | '/api/public/hooks/ticket-reminders'
  id:
    | '__root__'
    | '/'
    | '/_agentapp'
    | '/auth'
    | '/calculator'
    | '/discountvouchers'
    | '/inquiry'
    | '/mcp'
    | '/print-format'
    | '/services'
    | '/sitemap.xml'
    | '/templates'
    | '/verify-visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/agents'
    | '/admin/announcement'
    | '/admin/group-ticket-format'
    | '/admin/ok-to-board'
    | '/admin/queries'
    | '/admin/self-groups'
    | '/admin/tickets'
    | '/admin/visa-links'
    | '/admin/vouchers'
    | '/agent/login'
    | '/agent/register'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_agentapp/agent/admin'
    | '/_agentapp/agent/bookings'
    | '/_agentapp/agent/change-password'
    | '/_agentapp/agent/dashboard'
    | '/_agentapp/agent/fares'
    | '/_agentapp/agent/profile'
    | '/api/public/agent-approve'
    | '/api/public/hooks/ticket-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentappRoute: typeof AgentappRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  DiscountvouchersRoute: typeof DiscountvouchersRoute
  InquiryRoute: typeof InquiryRoute
  McpRoute: typeof McpRoute
  PrintFormatRoute: typeof PrintFormatRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  VerifyVisaRoute: typeof VerifyVisaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnnouncementRoute: typeof AdminAnnouncementRoute
  AdminGroupTicketFormatRoute: typeof AdminGroupTicketFormatRoute
  AdminOkToBoardRoute: typeof AdminOkToBoardRoute
  AdminQueriesRoute: typeof AdminQueriesRoute
  AdminSelfGroupsRoute: typeof AdminSelfGroupsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminVisaLinksRoute: typeof AdminVisaLinksRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentRegisterRoute: typeof AgentRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAgentApproveRoute: typeof ApiPublicAgentApproveRoute
  ApiPublicHooksTicketRemindersRoute: typeof ApiPublicHooksTicketRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-visa': {
      id: '/verify-visa'
      path: '/verify-visa'
      fullPath: '/verify-visa'
      preLoaderRoute: typeof VerifyVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-format': {
      id: '/print-format'
      path: '/print-format'
      fullPath: '/print-format'
      preLoaderRoute: typeof PrintFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discountvouchers': {
      id: '/discountvouchers'
      path: '/discountvouchers'
      fullPath: '/discountvouchers'
      preLoaderRoute: typeof DiscountvouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agentapp': {
      id: '/_agentapp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/register': {
      id: '/agent/register'
      path: '/agent/register'
      fullPath: '/agent/register'
      preLoaderRoute: typeof AgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visa-links': {
      id: '/admin/visa-links'
      path: '/admin/visa-links'
      fullPath: '/admin/visa-links'
      preLoaderRoute: typeof AdminVisaLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/self-groups': {
      id: '/admin/self-groups'
      path: '/admin/self-groups'
      fullPath: '/admin/self-groups'
      preLoaderRoute: typeof AdminSelfGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/admin/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ok-to-board': {
      id: '/admin/ok-to-board'
      path: '/admin/ok-to-board'
      fullPath: '/admin/ok-to-board'
      preLoaderRoute: typeof AdminOkToBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/group-ticket-format': {
      id: '/admin/group-ticket-format'
      path: '/admin/group-ticket-format'
      fullPath: '/admin/group-ticket-format'
      preLoaderRoute: typeof AdminGroupTicketFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcement': {
      id: '/admin/announcement'
      path: '/admin/announcement'
      fullPath: '/admin/announcement'
      preLoaderRoute: typeof AdminAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-approve': {
      id: '/api/public/agent-approve'
      path: '/api/public/agent-approve'
      fullPath: '/api/public/agent-approve'
      preLoaderRoute: typeof ApiPublicAgentApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agentapp/agent/profile': {
      id: '/_agentapp/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentappAgentProfileRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/fares': {
      id: '/_agentapp/agent/fares'
      path: '/agent/fares'
      fullPath: '/agent/fares'
      preLoaderRoute: typeof AgentappAgentFaresRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/dashboard': {
      id: '/_agentapp/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentappAgentDashboardRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/change-password': {
      id: '/_agentapp/agent/change-password'
      path: '/agent/change-password'
      fullPath: '/agent/change-password'
      preLoaderRoute: typeof AgentappAgentChangePasswordRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/bookings': {
      id: '/_agentapp/agent/bookings'
      path: '/agent/bookings'
      fullPath: '/agent/bookings'
      preLoaderRoute: typeof AgentappAgentBookingsRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/_agentapp/agent/admin': {
      id: '/_agentapp/agent/admin'
      path: '/agent/admin'
      fullPath: '/agent/admin'
      preLoaderRoute: typeof AgentappAgentAdminRouteImport
      parentRoute: typeof AgentappRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ticket-reminders': {
      id: '/api/public/hooks/ticket-reminders'
      path: '/api/public/hooks/ticket-reminders'
      fullPath: '/api/public/hooks/ticket-reminders'
      preLoaderRoute: typeof ApiPublicHooksTicketRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentappRouteChildren {
  AgentappAgentAdminRoute: typeof AgentappAgentAdminRoute
  AgentappAgentBookingsRoute: typeof AgentappAgentBookingsRoute
  AgentappAgentChangePasswordRoute: typeof AgentappAgentChangePasswordRoute
  AgentappAgentDashboardRoute: typeof AgentappAgentDashboardRoute
  AgentappAgentFaresRoute: typeof AgentappAgentFaresRoute
  AgentappAgentProfileRoute: typeof AgentappAgentProfileRoute
}

const AgentappRouteChildren: AgentappRouteChildren = {
  AgentappAgentAdminRoute: AgentappAgentAdminRoute,
  AgentappAgentBookingsRoute: AgentappAgentBookingsRoute,
  AgentappAgentChangePasswordRoute: AgentappAgentChangePasswordRoute,
  AgentappAgentDashboardRoute: AgentappAgentDashboardRoute,
  AgentappAgentFaresRoute: AgentappAgentFaresRoute,
  AgentappAgentProfileRoute: AgentappAgentProfileRoute,
}

const AgentappRouteWithChildren = AgentappRoute._addFileChildren(
  AgentappRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentappRoute: AgentappRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  DiscountvouchersRoute: DiscountvouchersRoute,
  InquiryRoute: InquiryRoute,
  McpRoute: McpRoute,
  PrintFormatRoute: PrintFormatRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  VerifyVisaRoute: VerifyVisaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnnouncementRoute: AdminAnnouncementRoute,
  AdminGroupTicketFormatRoute: AdminGroupTicketFormatRoute,
  AdminOkToBoardRoute: AdminOkToBoardRoute,
  AdminQueriesRoute: AdminQueriesRoute,
  AdminSelfGroupsRoute: AdminSelfGroupsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminVisaLinksRoute: AdminVisaLinksRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentRegisterRoute: AgentRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAgentApproveRoute: ApiPublicAgentApproveRoute,
  ApiPublicHooksTicketRemindersRoute: ApiPublicHooksTicketRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
